### PR TITLE
feat: Add support for admin access keys

### PR DESCRIPTION
**Pull request by zerok**
This should solve the use-case behind #61 .

### CODE REVIEW

**Comment by Seirdy** [comment]
It works wonderfully. Thank you.

Suggestion: it'd be nice to have tokens for a given user (eg `ci`) expire more rapidly than tokens for a browser session. Building my site takes seconds; a token for Hugo to use should expire within a minute. A token for a browser session could last for days.

**Comment by zerok** [comment]
> It works wonderfully. Thank you.

Awesome 😄 
 
> Suggestion: it'd be nice to have tokens for a given user (eg `ci`) expire more rapidly than tokens for a browser session. Building my site takes seconds; a token for Hugo to use should expire within a minute. A token for a browser session could last for days.

Good idea 🙂 I will update the TTL there and then finalize the PR afterwards.

**Comment by Seirdy** [comment]
LGTM; it's live on seirdy.one. I set the timeout to 2min, which is an order of magnitude longer than a typical Hugo run.

Even with a slow SSG like Jekyll: a whole hour seems way too much for a typical CI session, let alone a typical build. I suggest reducing the default TTL to 5min.

-- 
Seirdy (https://seirdy.one)

**Comment by zerok** [comment]
@Seirdy : Done. Thanks for testing 😄

**Comment by Seirdy** [comment]
Thank YOU! I'm back to having clean builds finish in 5-6 seconds thanks o this change (excluding static compression), of which the Hugo step is under 2 seconds. They used to take way longer.

**Pull request merged**
